# Generated by Django 6.1.1 on 2026-10-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("wave", models.PositiveIntegerField()),
                (
                    "monster_type",
                    models.CharField(default="To Be Completed", max_length=100),
                ),
                ("personality", models.TextField(default="To Be Completed")),
                ("interests", models.TextField(default="To Be Completed")),
                ("relationships", models.TextField(default="To Be Completed")),
                ("background", models.TextField(default="To Be Completed")),
                ("additional_information", models.TextField(default="To Be Completed")),
            ],
            options={
                "ordering": ["wave", "name"],
            },
        ),
    ]
